### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by skippyall** [skippyall/Technology-in-the-sea#1]
- [ ] Recipes:
  - [ ] Zinc
  - [ ] Gold
  - [ ] Applied Energistics
    - [x] Certus Quartz
  - [ ] Botania
    - [x] Cheap Bubbell & Underwater breathing charm
  - [ ] Recipe Mod Interaction
  - [x] Ad Astra Ore Veins
- [ ] Start Structure Generation
- [ ] Start Story
- [x] Less Drowned
- [x] Bosses (Aquatic)
- [ ] End Item (Aqua Shard)
